services:
  - type: web
    name: motionstory-api
    env: docker
    region: singapore
    plan: free
    dockerfilePath: ./api/Dockerfile
    dockerContext: ./api
    healthCheckPath: /health
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        value: motionstory
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: R2_ACCOUNT_ID
        sync: false
      - key: R2_ACCESS_KEY
        sync: false
      - key: R2_SECRET_KEY
        sync: false
      - key: R2_BUCKET_NAME
        value: motionstory-bucket
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: JWT_EXPIRATION_DAYS
        value: 7
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: False
